name: deploy-container
on:
  push:
    branches:
      - main
    paths:
        - 'container-udemy/**'

defaults:
  run:
    working-directory: container-udemy
        
jobs:
    build:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
        - run: npm install
        - run: npm run build

        - uses: chrislennon/action-aws-cli@v1.1
        - run: aws s3 sync dist s3://$AWS_S3_BUCKET_NAME/container-udemy
          env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
